### ISSUE TITLE
View multiple data files from remote host

### ISSUE THREAD

**Issue by carlfischerjba** [RandomFractals/geo-data-viewer#105]
Is there a way to view multiple data files from a remote host on the same map?

I have multiple geodata files in my project which is open in VSCode using the Remote SSH extension. I would like to drag and drop these shapefiles, csv files and rasters onto a map like I would in QGIS but in VSCode.

Currently, if I open a shapefile from the remote workspace via VSCode's file explorer, I get a button to "View Map" which is great but I can't see a way to add another data file to the same map. Dragging from the explorer onto the map only opens the file in a new tab and clicking "Add Data" only lets me browse local data (on my workstation, not on the remote server). There is an "Open Geo Data File" top left of the map tab which lets me type the path to a remote data file but it opens in a new tab.

**Comment by RandomFractals** [comment]
@carlfischerjba GeoDataViewer doesn't have any remote SSH extension integration, and I don't plan to add it.

It's designed only for working with local geo data files and some remote data URLs to initialize a map.

If you can see a data file in the built-in vscode file explorer, you should be able to add it to the map as another layer.

For example, I just tried creating a map from usa-state-capitals.csv (large blue dots) and then loaded usa-airports.csv data via kepler.gl + Add Data dialog (orange dots on the map):

![image](https://user-images.githubusercontent.com/656833/104846138-acac9280-589e-11eb-8b04-9f476bb52085.png)
