### ISSUE TITLE
provide custom NotebookOutputRenderer

### ISSUE THREAD

**Issue by AnWeber** [RandomFractals/geo-data-viewer#126]
It would be great if a [NotebookOutputRenderer](https://code.visualstudio.com/api/extension-guides/notebook#output-renderer) is offered. Use case is to make a Rest/ Http call in a notebook and to address this NotebookOutputRenderer directly with the received application/geo+json.

This implementation would already be possible with my extension [httpbook](https://marketplace.visualstudio.com/items?itemName=anweber.httpbook). As an example I have already tested the required interface with [httpbook-grid](https://marketplace.visualstudio.com/items?itemName=anweber.httpbook-grid).

If that change would be possible, I would be happy to assist with the necessary adjustments. I would find it great if it would work out. It would be very helpful for me.

**Comment by RandomFractals** [comment]
this will be done in a simpler [vscode-leaflet](https://github.com/RandomFractals/vscode-leaflet) extension I plan to work on this and next month.

As it is right now I don't plan to update GeoDataViewer beyond what it already offers, which is a lot.

If you'd like to submit a PR to do that with this keplergl, I'd be more than happy to review and merge when vscode notebooks API and UX go GA.

**Comment by RandomFractals** [comment]
@AnWeber you'd be happy to know I am going to work on keplergl map notebook renderer after all. 

See new repo here: https://github.com/RandomFractals/keplergl-notebook-renderer
