### ISSUE TITLE
Elevation data in gpx track leads to "swimming" track in map

### ISSUE THREAD

**Issue by danielscherzer** [RandomFractals/geo-data-viewer#140]
Thanks for your very usefull plugin!

When you load gpx track data that contains an <ele> tag (elevation info) the track stays not fixed to same map locations on panning the camera in the 2d or 3d view (swimming artifact). If you load the same track with removed <ele> tags everything is working as expected.

Example track once with and without <ele> tags: 
[Example.zip](https://github.com/RandomFractals/geo-data-viewer/files/9503895/Example.zip)

A simple workaround would be the option the ignore <ele> tags.

**Comment by RandomFractals** [comment]
@danielscherzer I can't reproduce what you are describing with the provided track `gpx` data files.

I loaded both of them into vscode v1.71.0 on Windows 10. What I see is a track displayed on the map. Some part of that track is in the water, but they both look the same to me when panning the map in 2d or 3d view. Both tracks move when panning the map, or zooming in and out.

![gpx-tracks](https://user-images.githubusercontent.com/656833/188852745-96d25831-f15b-498e-b813-de0c4eb4ae7c.gif)


So, I am not sure what  you mean by the "swimming artifact". Please verify your gpx data points of that track or create a recording of the issue you encountered.

**Comment by danielscherzer** [comment]
So sorry. This was my fault. I somehow sent you twice the file without the elevation data. Following is the file with elevation data:
[withEle.zip](https://github.com/RandomFractals/geo-data-viewer/files/9523233/withEle.zip)
I can see the swimming artifact best with the outdoor map style.

**Comment by ArnaudTa** [comment]
Hi I have the same issue, removing elevation `<ele>` solves it but it's a shame to have to remove it.
Maybe an option that removes it when generating geojson would be good enough

**Comment by RandomFractals** [comment]
We'll revisit this issue and stripping out elevation if it's not supported in the latest version of keplergl library and UI in the next Geo data viewer extension and libraries update and new Pro version we plan to release in fall. See #153 for more info on that.
