### ISSUE TITLE
Extension does not seem to be available on VSCode Marketplace

### ISSUE THREAD

**Issue by thib12** [RandomFractals/geo-data-viewer#151]
It seems that the extension is not available on the marketplace anymore (see https://marketplace.visualstudio.com/items?itemName=randomfractalsinc.geo-data-viewer).

**Comment by RandomFractals** [comment]
It's no longer available in VSCode marketplace.

You can still download and install the old `geo-data-viewer-2.6.0.vsix` extension package from our last release: https://github.com/RandomFractals/geo-data-viewer/releases

**Comment by RandomFractals** [comment]
It is back in VS Code marketplace now, and was republished and made accessible to the public again back in April:

https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.geo-data-viewer
