### ISSUE TITLE
Add support for default GeoJson style.

### ISSUE THREAD

**Issue by hlvlad** [RandomFractals/geo-data-viewer#158]
Hello, thanks for great extension.

Currently, if I open my GeoJson data consisting of few Polygons, they all are displayed with same fill color:
![image](https://github.com/RandomFractals/geo-data-viewer/assets/27830411/c6b649d6-2a81-4ca4-af6a-1ab0b2a1b3f5)

I can change their opacity or fill color manually using UI, but I have to do it each time I open new file. It would be great to have a VsCode setting which would allow me to set some default styles for my GeoJson data.

Regards, Vlad

**Comment by RandomFractals** [comment]
Will be resolved by map config auto-save as described in #160 in our new Pro Data Tools version of this extension later this summer.

Closing this as a duplicate for now.
