### ISSUE TITLE
Add simple editing support for opened files.

### ISSUE THREAD

**Issue by Qi2013** [RandomFractals/geo-data-viewer#159]
Would be great, if we can modify the elements shown in the layers.
As a first step, the nebula.gl can be used to create such editable layers.
Even if only specific type of layers and specific type of files can be opened for edition, it would helps a lot.

**Comment by RandomFractals** [comment]
@Qi2013 would map config auto-save with the latest kepler.gl 3.0 version support address your request?

See #160 and #141 for more info. Closing this as too broad of a feature request to consider otherwise.
