### ISSUE TITLE
hide kepler.gl export options

### ISSUE THREAD

**Issue by RandomFractals** [RandomFractals/geo-data-viewer#22]
since for some reason they don't work in vscode chromium v. for web views.

will provide custom map config and data sync instead in #20

**Comment by heshan0131** [comment]
none of the export works? or some works...

**Comment by RandomFractals** [comment]
none. I did not check my download folders tho. I did expect to get a Save As native file dialog.

Dialogs for save options to pick did show up nicely tho.

so, I am sure it's just some minor Electron app/Chromium disconnect ...

I'll probably just add custom toolbar to that map view since I need to add more vscode integration options for it.
