### ISSUE TITLE
remove add data kepler.gl modal dialog since we load it from opened vscode geo data text documents

### ISSUE THREAD

**Issue by RandomFractals** [RandomFractals/geo-data-viewer#38]
need to disable add data popup on initial map view load since we already load csv, geojson and map config via custom umd js calls. 

Just need to get rid of that modal, but have it available for adding more data later. see map.view.js for more info on the data loading parts ... 

https://github.com/RandomFractals/geo-data-viewer/blob/master/web/scripts/map.view.js#L165

**Comment by heshan0131** [comment]
if you want to get rid of the modal on initial render use 
```
const customReducer = keplerGlReducer.initialState({
  uiState: {
     currentModal: null
  }
});

```
