### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by marceloctorres** [RandomFractals/geo-data-viewer#86]
- Issue Type: `Performance`
- Extension Name: `geo-data-viewer`
- Extension Version: `1.8.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.45.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\mtorres\RandomFractalsInc.geo-data-viewer-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by RandomFractals** [comment]
some of it is expected depending on the geo data file size and map you are trying to load.
