### ISSUE TITLE
getting this message "Open a geo data file to view map"

### ISSUE THREAD

**Issue by vishalmhjn** [RandomFractals/geo-data-viewer#94]
I am trying to open a CSV file, but get the above message when I call the geo-data extension to launch the Kepler. But the file works fine with the Kepler web app.

**Comment by RandomFractals** [comment]
Geo data viewer provides map view & View Map context menu options for .csv files. 

Try some of the CSV files from this repository ./data/csv test files folder.

I am going close this issue as it doesn't have enough information to investigate.
